name: tp_client
description: A simple API client in Dart
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  http: ^0.13.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  tp_client:
    script: bin/client.dart
